name: 防止定时工作流被自动禁用

on:
  schedule:
    - cron: '45 14 4,19 * *'
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  keepalive:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: keep-active

      - name: 提交并推送空提交
        env:
          NAME: 'github-actions[bot]'
          EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
        run: |
          git -c user.name="$NAME" -c user.email="$EMAIL" commit --allow-empty -m '自动提交（保持活跃）'
          git push
